name: Auto update open PRs

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@5d273948c50bda6275d3a71e26f71c54e18392c1 # v0.8.1
        with:
          token: ${{ secrets.AUTOREBASE_TOKEN }}
          base: 'main'
          required_approval_count: 1
          require_passed_checks: false
          require_auto_merge_enabled: false
